# Generated by Django 3.1 on 2022-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='userid')),
                ('user_name', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='username')),
                ('user_age', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='userage')),
                ('user_email', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='useremail')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
