# Generated by Django 3.1 on 2022-02-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('type1', models.CharField(max_length=25, verbose_name='Type1')),
                ('type2', models.CharField(default='', max_length=25, verbose_name='Type2')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('heart_point', models.IntegerField(verbose_name='HP')),
                ('attack', models.IntegerField(verbose_name='Attack')),
                ('defense', models.IntegerField(verbose_name='Defense')),
                ('special_attack', models.IntegerField(verbose_name='Special Attack')),
                ('special_defense', models.IntegerField(verbose_name='Special Defense')),
                ('speed', models.IntegerField(verbose_name='Speed')),
                ('generation', models.IntegerField(verbose_name='The generation in which this pokemon first appears.')),
                ('is_legendary', models.BooleanField(verbose_name='If this pokemon is legendary or not.')),
            ],
            options={
                'db_table': 'pokemon',
            },
        ),
    ]
